# Docker container

pool:
  vmImage: ubuntu-latest

container: mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.14-WithNode-20210910135833-c401c85

steps:

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x'

- script: |
    echo $(System.ArtifactsDirectory)
    find $(System.ArtifactsDirectory) -type f
  displayName: 'Print SystemArtifactsDirectory'

- script: |
    echo $(System.ArtifactsDirectory)
    find $(System.ArtifactsDirectory) -type f
  displayName: 'Print SystemArtifactsDirectory'

- task: ManifestGeneratorTask@0
  inputs:
    BuildDropPath: '$(System.ArtifactsDirectory)'
    Verbosity: 'Verbose'
    AdditionalComponentDetectorArgs: "--DirectoryExclusionList **/samples/**"

- script: |
    echo $(System.ArtifactsDirectory)
    find $(System.ArtifactsDirectory) -type f
  displayName: 'Print SystemArtifactsDirectory'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.ArtifactsDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- script: |
    echo $(System.ArtifactsDirectory)
    find $(System.ArtifactsDirectory) -type f
  displayName: 'Print SystemArtifactsDirectory'

- task: DropValidatorTask@0
  inputs:
    BuildDropPath: '$(System.ArtifactsDirectory)'
    OutputPath: '$(System.ArtifactsDirectory)/output.json'
    ValidateSignature: true
    Verbosity: 'Verbose'

- script: |
    echo $(System.ArtifactsDirectory)
    find $(System.ArtifactsDirectory) -type f
  displayName: 'Print SystemArtifactsDirectory'

